- README.md
> readme updata 環境記入

- docker-compose.yml
- rails_app/Dockerfile
* Docker image を再度作成しコンテナ起動を確認. ( 一度削除していた為)
> ./_install.shを実行

- rails_app/app/controllers/application_controller.rb
- rails_app/app/models/user.rb
- rails_app/config/initializers/devise_token_auth.rb
- rails_app/config/routes.rb
- rails_app/db/migrate/20210317132119_devise_token_auth_create_users.rb
- rails_app/db/schema.rb
* **user model** を devise_token_auth のコマンドで生成
* **migration** を実行
user model 生成コマンド
```ruby
$ bundle exec rails g devise_token_auth:install User auth
```
> users model の生成

- rails_app/app/models/user.rb
- rails_app/db/migrate/20210317132119_devise_token_auth_create_users.rb
- rails_app/db/schema.rb
* **users table** に構成表で作成した **column** を追加
> users model columns の修正

- rails_app/app/models/calendar.rb
- rails_app/app/models/deliverie.rb
- rails_app/app/models/question_answer.rb
- rails_app/app/models/reservation.rb
- rails_app/app/models/store.rb
- rails_app/app/models/store_discount_info_notification.rb
- rails_app/app/models/user.rb
- rails_app/app/models/word_mouth.rb
- rails_app/config/routes.rb
- rails_app/db/migrate/20210318072954_create_reservations.rb
- rails_app/db/migrate/20210318113830_create_word_mouths.rb
- rails_app/db/schema.rb
- rails_app/spec/factories/calendars.rb
- rails_app/spec/factories/deliveries.rb
- rails_app/spec/factories/question_answers.rb
- rails_app/spec/factories/reservations.rb
- rails_app/spec/factories/store_discount_info_notifications.rb
- rails_app/spec/factories/word_mouths.rb
- rails_app/spec/models/calendar_spec.rb
- rails_app/spec/models/deliverie_spec.rb
- rails_app/spec/models/question_answer_spec.rb
- rails_app/spec/models/reservation_spec.rb
- rails_app/spec/models/store_discount_info_notification_spec.rb
- rails_app/spec/models/word_mouth_spec.rb
* モデルを作成したので、`db:migrate` を実行
日付入力の型が分からないので、stirng で代用
* **timestamps** を **string** に修正
* **int** を **integer** に修正
> db:migrate を実行

- rails_app/app/models/user.rb
- rails_app/spec/spec_helper.rb
* User model **validation 設定** /  ( **修正は必須** )
* テストが失敗しても最後まで処理が走る設定
> Set user model validation

- _roothome/.bashrc
- rails_app/Gemfile
- rails_app/Gemfile.lock
- rails_app/spec/factories/user.rb
- rails_app/spec/models/user_spec.rb
- rails_app/spec/rails_helper.rb
* Faker を使用
* **gem** `gimei`を install  Faker で 「フリガナ」使用可能にした
* Faker **日本語** 対応
* user モデルテストは不十分
> User model テストを実装(仮)

- rails_app/app/controllers/api/v1/auth/registrations_controller.rb
- rails_app/app/controllers/api/v1/base_api_controller.rb
- rails_app/app/controllers/application_controller.rb
- rails_app/app/models/user.rb
- rails_app/config/initializers/devise_token_auth.rb
- rails_app/config/routes.rb
- rails_app/db/migrate/20210317132119_devise_token_auth_create_users.rb
- rails_app/db/schema.rb
- rails_app/spec/models/user_spec.rb
- rails_app/spec/requests/api/v1/auth/registrations_spec.rb
- rails_app/spec/requests/api/v1/base_api_spec.rb
* user登録に合わせ routes を設定
* 認証機能の設定をコメントイン & カラム追加
* 認証機能のコントローラファイルを生成
> User 認証機能を実装

- rails_app/app/controllers/api/v1/auth/registrations_controller.rb
- rails_app/app/models/user.rb
* User登録機能を実装
* `validates` を設定
```js
{
"name": "Cloud",
"email": "user8@x-hack.com",
"furigana": "クラウド",
"tel": "1234567890",
"birthday": "20210325",
"six": "女",
"address": "大阪市",
"password": "123456",
"password_confirmation": "123456"
}
```
> User登録機能を実装

- rails_app/app/controllers/api/v1/auth/registrations_controller.rb
- rails_app/app/controllers/api/v1/auth/sessions_controller.rb
- rails_app/app/controllers/api/v1/users/auth/sessions_controller.rb
- rails_app/config/routes.rb
- rails_app/spec/requests/api/v1/auth/registrations_spec.rb
- rails_app/spec/requests/api/v1/auth/sessions_spec.rb
- rails_app/spec/requests/api/v1/users/auth/sessions_spec.rb
* User認証の階層は `auth`で切り分けていたので `users/auth`とする必要がなかった
* Store認証は `stores_auth`で切り分けている
> User controllerの階層を修正

- rails_app/app/models/store.rb
- rails_app/app/models/user.rb
> Store model のバリテーションを設定

- rails_app/app/controllers/api/v1/store_auth/sessions_controller.rb
- rails_app/spec/requests/api/v1/store_auth/sessions_spec.rb
* 店舗 ログイン・ログアウトの実装
```bash
$ bundle exec rails g controller api/v1/store_auth/sessions
```
> 店舗ログイン・ログアウトの実装

- rails_app/spec/requests/api/v1/store_auth/sessions_spec.rb
> Fix rubocop を実行

- rails_app/spec/factories/store.rb
- rails_app/spec/models/store_spec.rb
* 店舗モデルの正常系テストの実装
* **FactoryBot : store** ファイルを生成
> 店舗モデル正常系モデルの実装

- .env
- .gitignore
* 開発環境であるため。環境変数ファイルをGit管理下とした。
* https://github.com/RaiseTech-team01/reservation_app/issues/36
> git管理下に変更。環境ファイル

- rails_app/app/models/reservation.rb
> Reservation model validates の設定

- rails_app/app/models/deliverie.rb
- rails_app/app/models/reservation.rb
- rails_app/app/models/word_mouth.rb
- rails_app/db/migrate/20210318072954_create_reservations.rb
- rails_app/db/migrate/20210318113830_create_word_mouths.rb
- rails_app/db/schema.rb
- rails_app/spec/factories/reservations.rb
- rails_app/spec/factories/word_mouths.rb
- rails_app/spec/models/reservation_spec.rb
- rails_app/spec/models/store_spec.rb
- rails_app/spec/models/word_mouth_spec.rb
* **reservations 予約** : `date_at`, `date_on` を  `string` 型から `datetime `型 に修正
* **word_mouths クチコミ** :  `visit_ day` を`string` 型から `datetime` 型 に修正
```ruby
$ bundle exec rails db:migrate:reset
```
> バリテーション,  データ型の修正

- rails_app/app/models/calendar.rb
- rails_app/app/models/deliverie.rb
- rails_app/app/models/question_answer.rb
- rails_app/app/models/store_discount_info_notification.rb
- rails_app/app/models/word_mouth.rb
　対象モデルのバリテーションを設定
* Deliverie
* WordMouth
* QuestionAnswer
* Calendar
* StoreDiscountInfoNotification
> 各モデルのバリテーションを設定

- rails_app/app/models/payment.rb
- rails_app/app/models/reservation.rb
- rails_app/db/migrate/20210328133435_create_payments.rb
- rails_app/db/schema.rb
- rails_app/spec/factories/payments.rb
- rails_app/spec/models/payment_spec.rb
* payment model の実装
```ruby
$  bundle exec rails g model payment
```
> payment model の実装

- rails_app/spec/factories/reservations.rb
- rails_app/spec/models/reservation_spec.rb
* FactoryBot の設定
* reservation model 正常系テストの実装
> reservation model の正常系テストを実装

- _roothome/.pryrc
- rails_app/app/models/deliverie.rb
- rails_app/db/migrate/20210318112306_create_deliveries.rb
- rails_app/db/schema.rb
- rails_app/spec/factories/calendars.rb
- rails_app/spec/factories/deliveries.rb
- rails_app/spec/factories/question_answers.rb
- rails_app/spec/factories/store_discount_info_notifications.rb
- rails_app/spec/factories/word_mouths.rb
- rails_app/spec/models/calendar_spec.rb
- rails_app/spec/models/deliverie_spec.rb
- rails_app/spec/models/question_answer_spec.rb
- rails_app/spec/models/store_discount_info_notification_spec.rb
- rails_app/spec/models/word_mouth_spec.rb
* モデルテストの実装：正常系のみ
* `_roothome/.pryrc ` に debug の alias 設定を入れた
> model test 正常系の実装

- rails_app/spec/requests/api/v1/auth/registrations_spec.rb
- rails_app/spec/requests/api/v1/store_auth/registrations_spec.rb
* User 登録 異常系テスト項目を追加：値が空である時のバリテーションテスト
> user 登録 異常系テスト追加

- rails_app/app/models/store.rb
> Fix: fax に空のバリテーションはいらない

- rails_app/app/controllers/api/v1/store/reservations_controller.rb
- rails_app/app/serializers/api/v1/reservation_show_serializer.rb
- rails_app/bin/webpack
- rails_app/bin/webpack-dev-server
- rails_app/spec/requests/home_spec.rb
* 指定予約店舗の詳細表示を実装
* show serializers の設定
* show controller の実装
* 生成コマンド
```ruby
$ bundle exec rails g serializer Api/V1/ReservationShow
```
* API
```bash
http://localhost:3000/api/v1/store/store/:store_id/reservations/:id
ex) 
http://localhost:3000/api/v1/store/store/2/reservations/2
```
* 実装メモ：[🔖 指定店舗の指定予約詳細表示](https://www.notion.so/9a8cce4fd3ce46e2837d2ae0dfd521cb#645da6f9d48041059d3a6843813e73b9)
> [RAISETECH-18] 指定予約店舗の詳細表示を実装

- rails_app/app/javascript/components/Registration.vue
- rails_app/app/javascript/components/RegistrationConfirm.vue
- rails_app/app/javascript/router/router.js
- rails_app/config/routes.rb
* アカウント確認画面の追加（html）
* アカウント確認画面を追加
* ルーターの更新
* なし
> [RAISETECH-71] アカウント確認画面

- rails_app/app/javascript/components/RegistrationCompletion.vue
- rails_app/app/javascript/router/router.js
- rails_app/config/routes.rb
* アカウント登録完了画面を作成する
* アカウント登録完了画面のHTMLコード作成
* ルーター側の設定
* 対応後の画面
* （添付予定）
> [RAISETECH-72] アカウント登録完了画面

- rails_app/spec/models/reservation_spec.rb
* タイトル通り
* バリテーションのテスト
* 正常系
* 異常系
* 関数のテスト
> [RAISETECH-64] 予約モデルの実装

- rails_app/app/javascript/components/AccountInfo.vue
- rails_app/app/javascript/router/router.js
- rails_app/config/routes.rb
* アカウント情報画面の作成（HTML）
* アカウント情報画面の作成（HTML）
* ルーター設定
* 表示画面
* ![image](https://user-images.githubusercontent.com/3205581/118772625-ee862d80-b8be-11eb-9009-48084149d32f.png)
> [RAISETECH-73] アカウント情報画面

- rails_app/app/serializers/api/v1/store_serializer.rb
- rails_app/app/serializers/api/v1/user_serializer.rb
- rails_app/config/routes.rb
- rails_app/spec/factories/reservations.rb
- rails_app/spec/requests/api/v1/reservations_spec.rb
- rails_app/spec/spec_helper.rb
*タイトル通り
* PR出し直し
* 予約機能テストの実装
* 正常系
* 異常系 
* [RAISETECH-65] 予約リクエストテストの実装 #79
Git：pull 操作に失敗したのでPR出し直し
-    [x] Rspec
-    [x] rubocop
> [RAISETECH-65] 予約リクエストテストの実装2 

- rails_app/app/models/user.rb
- rails_app/spec/models/user_spec.rb
* タイトル通り
* バリテーションのテストを実装
* 正常系
* 異常系
OKなら、チェック
> [RAISETECH-55] User model のテストを実装

- rails_app/app/models/store.rb
- rails_app/spec/models/store_spec.rb
* タイトル通り
* Store モデルのテストを実装
* 正常系
* 異常系
* `seat`のバリテーションを修正
OKなら、チェック
> [RAISETECH-55] Store model のテストを実装

- rails_app/app/javascript/components/Login.vue
- rails_app/app/packs/packs/application.js
> [RAISETECH-84] ログイン画面 

- rails_app/app/javascript/components/Login.vue
* ログイン処理が失敗していたので修正
* user, passの取得失敗部分を修正した
* なし
OKなら、チェック
> [RAISETECH-84] ログイン画面

- rails_app/app/controllers/api/v1/reservations_controller.rb
- rails_app/app/models/store.rb
- rails_app/db/migrate/20210318043433_devise_token_auth_create_stores.rb
- rails_app/db/schema.rb
- rails_app/db/seeds.rb
- rails_app/spec/models/store_spec.rb
- rails_app/spec/requests/api/v1/reservations_spec.rb
* マージ先を `orgin/main` に修正
* 認識不足によるPR作成
* https://github.com/RaiseTech-team01/reservation_app/pull/96#issuecomment-855236130
> [RAISETECH-41] 予約座席数の操作(再)

- rails_app/app/javascript/components/ReservationList.vue
- rails_app/app/javascript/router/router.js
- rails_app/config/routes.rb
* 予約一覧画面の作成（CSS）
* 予約一覧画面を作成し、CSSを適用する
OKなら、チェック
> [RAISETECH-74] 予約一覧画面

- rails_app/app/javascript/components/ReservationForm.vue
- rails_app/app/javascript/components/dialog/Timetable.vue
* 予約登録画面の時間帯ダイアログを追加（CSS対応）
* 予約登録画面で時間帯の選択ボックスを押下すると、時間帯ダイアログが表示されるように変更
OKなら、チェック
> [RAISETECH-80] 予約登録画面_時間帯

- rails_app/app/javascript/components/layout/Header.vue
* ログアウト機能の枠組みを追加（CSS）
* ヘッダーの右側に人型アイコンを表示
* ログイン状態に応じて表示を切り替える仕組みを追加
* ログイン状態：アイコンが金色
* 非ログイン状態：アイコンが灰色
* ログイン状態に応じてアイコンタップ時に表示するメニューの内容を変更
* ログイン状態：「ログアウト」を表示
* 非ログイン状態：「ログイン」を表示
※ヘッダ部分を参照
※ヘッダ部分を参照
OKなら、チェック
> [RAISETECH-87] ログアウト機能

- rails_app/app/controllers/api/v1/reservations_controller.rb
- rails_app/config/routes.rb
- rails_app/spec/requests/api/v1/reservations_spec.rb
* タイトル通り
* [【Rails】 updateメソッドの使い方を徹底解説！](https://pikawaka.com/rails/update)
OKなら、チェック
> [RAISETECH-41] 予約キャンセルの処理、座席数を増やす

- rails_app/app/controllers/api/v1/reservations_controller.rb
- rails_app/config/routes.rb
- rails_app/spec/requests/api/v1/reservations_spec.rb
* タイトル通り
* 座席変更数を反映
* テストの修正
OKなら、チェック
> [RAISETECH-41] 予約更新処理の修正

- rails_app/app/javascript/components/store/StoreAccountConfirm.vue
- rails_app/app/javascript/components/store/StoreAccountForm.vue
- rails_app/app/javascript/components/store/StoreDashBoard.vue
- rails_app/app/javascript/components/store/StoreSettings.vue
- rails_app/app/javascript/components/store/StoreUserList.vue
- rails_app/app/javascript/components/store/UserList.vue
- rails_app/app/javascript/router/router.js
- rails_app/config/routes.rb
* 管理画面系の画面を作成
* 管理画面系の下記の画面を作成した
* ユーザ一覧画面
* アカウント登録確認画面
* ダッシュボード画面
* 設定画面
OKなら、チェック
> [RAISETECH-48] 6管理画面_UIデザイン

- rails_app/app/javascript/components/AccountEdit.vue
- rails_app/app/javascript/components/AccountInfo.vue
- rails_app/app/javascript/components/RegistrationCompletion.vue
- rails_app/app/javascript/components/RegistrationConfirm.vue
- rails_app/app/javascript/components/RegistrationForm.vue
- rails_app/app/javascript/components/ReservationCompletion.vue
- rails_app/app/javascript/components/ReservationConfirm.vue
- rails_app/app/javascript/components/ReservationDetail.vue
- rails_app/app/javascript/components/ReservationEdit.vue
- rails_app/app/javascript/components/ReservationForm.vue
- rails_app/app/javascript/components/ReservationHistory.vue
- rails_app/app/javascript/components/ReservationList.vue
- rails_app/app/javascript/components/ReservationViewHistory.vue
- rails_app/app/javascript/components/layout/Header.vue
- rails_app/app/javascript/components/layout/Navigation.vue
- rails_app/app/javascript/components/layout/StoreHeader.vue
- rails_app/app/javascript/components/store/StoreAccountConfirm.vue
- rails_app/app/javascript/components/store/StoreAccountForm.vue
- rails_app/app/javascript/components/store/StoreDashBoard.vue
- rails_app/app/javascript/components/store/StoreLogin.vue
- rails_app/app/javascript/components/store/StoreSettings.vue
- rails_app/app/javascript/router/router.js
- rails_app/config/routes.rb
* 画面遷移処理の実装
* ユーザ系画面への画面遷移処理を追加
* 管理系画面への画面遷移処理を追加
*
OKなら、チェック
> [RAISETECH-91] 画面遷移処理の実装
